require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PostsController do

  # This should return the minimal set of attributes required to create a valid
  # Post. As you add validations to Post, be sure to
  # update the return value of this method accordingly.
  describe '#index' do
    context 'when not signed in' do
      it 'redirects to admin signin path' do
        get :index
        response.should redirect_to new_admin_session_path
      end  
    end  
    context 'when signed in as user' do
      it 'redirects to admin signin path' do
        sign_in Factory(:user)
        get :index
        response.should redirect_to new_admin_session_path
      end  
    end  
    context 'when signed in as admin' do
      it "assigns all posts as @posts" do
        sign_in Factory(:admin)        
        post = Factory(:post)
        get :index
        # assigns(:posts).should eq([post]) # => Fails !!
        # actually, redirects to new_admin_session_path although admin is signed in !!
         response.should_not redirect_to new_admin_session_path
      end
    end
  end
end
